### ISSUE TITLE
s

### ISSUE THREAD

**Issue by GokseLW** [CTK-WARRIOR/Guide-discord.js-v12#2]
![image](https://user-images.githubusercontent.com/57256097/82804418-f0bfd280-9e8a-11ea-8188-0e18aa69555c.png)

**Comment by khtbd** [comment]
I have been getting the same error. Do you have a fix for it, or are you still waiting on someone to help?

**Comment by khtbd** [comment]
To fix this issue, you have to just copy and paste the xp.js file as is. do not add or remove anything. just copy and paste it and you are good.
