### ISSUE TITLE
I am getting exit1 error

### ISSUE THREAD

**Issue by maximoffgaming** [CTK-WARRIOR/Guide-discord.js-v12#8]
code ELIFECYCLE
npm ERR! errno 1
npm ERR! mybot@1.0.0 start: `node ./server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mybot@1.0.0 start script.

Iam getting this error what should I do

**Comment by tlakshya9** [comment]
Same bro
